version: "3.8"
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build: ./auth
    container_name: auth_service
    ports:
      - "3000:3000"
    env_file:
      - ./auth/.env
    depends_on:
      - mongodb
      - rabbitmq

  product:
    build: ./product
    container_name: product_service
    ports:
      - "3001:3001"
    env_file:
      - ./product/.env
    depends_on:
      - mongodb
      - rabbitmq

  order:
    build: ./order
    container_name: order_service
    ports:
      - "3002:3002"
    env_file:
      - ./order/.env
    depends_on:
      - mongodb
      - rabbitmq
      - product
      - auth
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth
      - product
      - order

volumes:
  mongo_data:
